[package]
name = "turiplogic"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.0"
dear-imgui-rs = "0.10.4"
env_logger = "0.11.10"
generational-arena = "0.2.9"
glam = { version = "0.32.1", features = ["mint"] }
imgui = "0.12.0"
imgui-wgpu = "0.28.0"
imgui-winit-support = "0.13.0"
mint = "0.5.9"
palette = "0.7.6"
pollster = "0.4.0"
strum = { version = "0.28", features = ["derive"] }
wgpu = "29.0.1"
winit = "0.30.13"
